/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ApiErrorResponse */
    'def-0': {
      /** @example 400 */
      statusCode: number;
      /** @example Validation Error */
      message: string;
      /** @example Bad Request */
      error: string;
      /** @example YevPQs */
      correlationId: string;
      /**
       * @description Optional list of sub-errors
       * @example incorrect email
       */
      subErrors?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
